port: 8080
storage_type: memory  # postgres или memory
database_url: "postgres://postgres:password@localhost:5432/shortener?sslmode=disable"
redis_addr: "localhost:6379"
redis_password: ""
short_code_length: 10
rate_limit_max: 100
rate_limit_window_sec: 60
bloom_n: 1000000
bloom_p: 0.001
domain: "http://localhost:8080"
enable_metrics: true