// Code generated by MockGen. DO NOT EDIT.
// Source: ../bloom_filter.go
//
// Generated by this command:
//
//	mockgen -source=../bloom_filter.go -destination=mock_bloom_filter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBloomFilter is a mock of BloomFilter interface.
type MockBloomFilter struct {
	ctrl     *gomock.Controller
	recorder *MockBloomFilterMockRecorder
	isgomock struct{}
}

// MockBloomFilterMockRecorder is the mock recorder for MockBloomFilter.
type MockBloomFilterMockRecorder struct {
	mock *MockBloomFilter
}

// NewMockBloomFilter creates a new mock instance.
func NewMockBloomFilter(ctrl *gomock.Controller) *MockBloomFilter {
	mock := &MockBloomFilter{ctrl: ctrl}
	mock.recorder = &MockBloomFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBloomFilter) EXPECT() *MockBloomFilterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBloomFilter) Add(data []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", data)
}

// Add indicates an expected call of Add.
func (mr *MockBloomFilterMockRecorder) Add(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBloomFilter)(nil).Add), data)
}

// Test mocks base method.
func (m *MockBloomFilter) Test(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Test", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Test indicates an expected call of Test.
func (mr *MockBloomFilterMockRecorder) Test(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Test", reflect.TypeOf((*MockBloomFilter)(nil).Test), data)
}
